import argparse
import glob
import os
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("❌ CHYBA: Proměnná GEMINI_API_KEY nebyla v .env souboru nalezena!")

http_proxy = os.getenv("HTTP_PROXY") or os.getenv("http_proxy")
if http_proxy:
    os.environ["HTTP_PROXY"] = http_proxy
    os.environ["HTTPS_PROXY"] = os.getenv("HTTPS_PROXY") or http_proxy

client = genai.Client(api_key=api_key)

REPO_URL = "https://github.com/maravondra/cv-ai-generator"

AI_DISCLAIMER_MD = {
    "cs": (
        "\n\n---\n\n"
        "🤖 *Tento motivační dopis byl vygenerován AI agentem, kterého vyvinul Marek Vondra. "
        f"Podrobný popis, jak agent funguje: [{REPO_URL.split('//', 1)[1]}]({REPO_URL})*\n"
    ),
    "en": (
        "\n\n---\n\n"
        "🤖 *This cover letter was generated by an AI agent built by Marek Vondra. "
        f"Details on how the agent works: [{REPO_URL.split('//', 1)[1]}]({REPO_URL})*\n"
    ),
}

CZECH_CHARS = set("áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ")


def detect_language(text):
    """Rozpozná jazyk zdrojového CV podle podílu znaků s českou diakritikou
    (stejná logika jako v render_cv_pdf.py)."""
    total_alpha = sum(1 for c in text if c.isalpha())
    if not total_alpha:
        return "cs"
    czech_count = sum(1 for c in text if c in CZECH_CHARS)
    return "cs" if (czech_count / total_alpha) > 0.01 else "en"


def load_cv(filepath):
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"❌ CV soubor nebyl nalezen: '{filepath}'")
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()


def guess_job_description_path(cv_filepath, jd_dir="./job_descriptions"):
    """Odvodí název souboru s inzerátem z názvu CV, např.
    'CV_Marek_Vondra_CeskaSporitelna_TribeITLead_EN.md' -> 'CeskaSporitelna_TribeITLead.md'."""
    base = os.path.splitext(os.path.basename(cv_filepath))[0]
    if base.startswith("CV_Marek_Vondra_"):
        base = base[len("CV_Marek_Vondra_"):]
    if base.endswith("_EN"):
        base = base[: -len("_EN")]
    candidate = os.path.join(jd_dir, base + ".md")
    return candidate if os.path.exists(candidate) else None


def load_job_description(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()


def generate_cover_letter(cv_filepath, job_filepath=None, output=None):
    cv_text = load_cv(cv_filepath)
    lang = detect_language(cv_text)
    lang_name = "češtině" if lang == "cs" else "angličtině"
    print(f"🌐 Jazyk CV: {lang} → dopis se vygeneruje v {lang_name}.")

    if not job_filepath:
        job_filepath = guess_job_description_path(cv_filepath)

    job_description = ""
    if job_filepath and os.path.exists(job_filepath):
        print(f"📖 Načítám popis pozice z: {job_filepath}")
        job_description = load_job_description(job_filepath)
    else:
        print("⚠️ Popis pozice nebyl nalezen, dopis vznikne pouze z obsahu CV.")

    prompt = f"""
    Jsi špičkový executive kariérní poradce. Na základě přiloženého CV (a případně
    popisu pracovní pozice) napiš profesionální, úderný a osobitý motivační dopis
    pro kandidáta Marka Vondru.

    ### JAZYK DOPISU:
    Piš celý dopis v {lang_name} – ve stejném jazyce, v jakém je napsané CV níže.

    ### CV KANDIDÁTA:
    {cv_text}

    ### POPIS PRACOVNÍ POZICE (pokud je k dispozici):
    {job_description or "(popis pozice není k dispozici, vycházej pouze z CV)"}

    ---

    ### POKYNY PRO NAPSÁNÍ DOPISU:
    1. **Formát:** Standardní struktura motivačního/průvodního dopisu v Markdownu –
       oslovení, 3-4 odstavce těla dopisu, závěrečná výzva k akci, pozdrav a podpis
       "Marek Vondra". Bez nadpisů typu H1/H2, jde o dopis, ne o CV.
    2. **Obsah:** Propoj konkrétní zkušenosti a úspěchy z CV s požadavky dané pozice
       (pokud je popis pozice k dispozici). Vyzdvihni to, co kandidáta odlišuje –
       vedení velkých týmů, cloudovou/AI transformaci, obchodní dopad.
    3. **Tón:** Sebevědomý, věcný, bez klišé a bez zbytečné okázalosti. Konkrétní
       místo obecného.
    4. **Délka:** Zhruba 300–400 slov, aby se dopis vešel na jednu stranu.

    Vygeneruj kompletní čistý Markdown výstup bez jakéhokoliv úvodního nebo
    závěrečného komentáře.
    """

    print("🤖 Generuji motivační dopis pomocí AI (Gemini 3.6 Flash)...")
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.4,
        ),
    )

    letter_content = response.text.strip() + AI_DISCLAIMER_MD[lang]

    if output:
        output_path = output
    else:
        cv_base = os.path.splitext(os.path.basename(cv_filepath))[0]
        letter_name = cv_base.replace("CV_", "CoverLetter_", 1) if cv_base.startswith("CV_") else f"CoverLetter_{cv_base}"
        output_path = f"{letter_name}.md"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(letter_content)

    print(f"✅ Motivační dopis byl uložen do: {output_path}")
    return output_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Vygeneruje motivační dopis (Markdown) na základě existujícího CV."
    )
    parser.add_argument("md_file", type=str, help="Cesta k .md souboru s CV (např. CV_Marek_Vondra_...md)")
    parser.add_argument(
        "--job", type=str, default=None,
        help="Volitelná cesta k souboru s popisem pozice (výchozí: dohledá se automaticky v ./job_descriptions)",
    )
    parser.add_argument(
        "--output", "-o", type=str, default=None,
        help="Volitelná cesta k výstupnímu souboru (výchozí: CoverLetter_<název_CV>.md)",
    )
    args = parser.parse_args()
    generate_cover_letter(args.md_file, args.job, args.output)
